"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Clock3, FileCheck2, Info } from "lucide-react";
import { useRouter } from "next/navigation";
import type { SessionUser } from "@/lib/auth";
import { AppShell } from "@/components/AppShell";

export function StudentPortal({ user }: { user: SessionUser }) {
  const router = useRouter(); const [exams, setExams] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [starting, setStarting] = useState("");
  async function load() { try { const response = await fetch("/api/student/exams", { cache: "no-store" }); if (response.status === 401) { window.location.assign("/login"); return; } if (!response.ok) throw new Error("Exam request failed"); const data = await response.json(); setExams(data.exams ?? []); } catch (error) { console.error(error); } finally { setLoading(false); } }
  useEffect(() => { load(); fetch("/api/ping", { method: "POST" }); const id = window.setInterval(() => fetch("/api/ping", { method: "POST" }), 30_000); return () => window.clearInterval(id); }, []);
  async function start(examId: string) { setStarting(examId); try { const response = await fetch(`/api/exams/${examId}/start`, { method: "POST" }); const data = await response.json().catch(() => ({})); if (response.ok) router.push(`/student/exam/${data.attemptId}`); } catch (error) { console.error(error); } finally { setStarting(""); } }
  return <AppShell user={user} label="STUDENT / PESERTA"><div className="page-heading student-heading"><div><span className="eyebrow">STUDENT PORTAL / READY</span><h1>Halo, <span className="accent-text">{user.name?.split(" ")[0] || user.username}</span>.</h1><p className="muted">Pilih ujian yang tersedia. Fokus, baca teliti, lalu jawab dengan tenang.</p></div><div className="student-id"><span>NO. ABSEN</span><strong>{String(user.absenNumber ?? "—").padStart(2, "0")}</strong></div></div><div className="notice-card"><Info size={20} /><div><strong>Petunjuk singkat</strong><p>Urutan soal diacak secara unik saat ujian dimulai dan tetap sama saat halaman di-refresh. Jangan menutup halaman sebelum menekan selesai.</p></div></div><section><div className="section-label"><span className="card-kicker">AVAILABLE EXAMS</span><span>{exams.length} ujian tersedia</span></div>{loading ? <div className="loading-block">Memuat daftar ujian...</div> : <div className="student-exam-grid">{exams.map((exam) => <article className="exam-card brutal-card" key={exam.id}><div className="exam-card-top"><span className="exam-icon"><BookOpen size={22} /></span>{exam.latestAttempt?.endTime && <span className="completed-tag"><FileCheck2 size={14} /> Selesai</span>}</div><h2>{exam.title}</h2><p className="muted">{exam.description || "Ujian berbasis komputer dengan penilaian otomatis."}</p><div className="exam-meta"><span><BookOpen size={15} /> {exam.questionCount} soal</span><span><Clock3 size={15} /> {exam.duration} menit</span></div><button className="primary-button full" onClick={() => start(exam.id)} disabled={starting === exam.id || !!exam.latestAttempt?.endTime}>{starting === exam.id ? "Menyiapkan soal..." : exam.latestAttempt?.endTime ? `Nilai: ${exam.latestAttempt.score}` : "Mulai ujian"}<ArrowRight size={17} /></button></article>)}</div>}{!loading && exams.length === 0 && <div className="empty-state">Belum ada ujian yang dipublikasikan.</div>}</section></AppShell>;
}
